version: '3'

services:
  django:
    build:
      context: ./backend
    command: bash -c "uvicorn  main:app --host 0.0.0.0 --port 8000"
    restart: always
    ports:
      - 192.168.0.254:8000:8000
